name: easy_localization_generator
description: Download CSV file and generates the localization keys from an online Google Sheet.
version: 0.0.2
# author: Rin Luu Van <rinlv.hn@gmail.com>
homepage: https://github.com/rinlv/easy_localization_generator
issue_tracker: https://github.com/rinlv/easy_localization_generator/issues

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter
  analyzer: ^4.2.0
  build: ^2.3.0
  build_config: ^1.1.0
  source_gen: ^1.2.2
  http: ^0.13.4
  path: ^1.8.1
  csv: ^5.0.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter